import type { Metadata } from "next";
import { fonts } from '@/app/fonts'
import { Providers } from '@/app/providers'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fonts.rubik.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
